### ISSUE TITLE
When wal colors are updated PyCharm GUI colors change automatically but editor colors don't 

### ISSUE THREAD

**Issue by kureta** [Mr-SD/intellijPywal#2]
I have to re-import material-pywal.icls for color changes to effect the editor section of PyCharm window.

**Comment by 0x6C38** [comment]
Do you have to reload the editor color scheme even after restarting PyCharm? What version of PyCharm are you using? Are you on Linux?

**Comment by kureta** [comment]
I am on Arch linux. PyCharm Professional Edition 2018.2.1. After a restart PyCharm's GUI colors (colors menu items etc. everything outside the editor area) change but editor colors stay the same. Then I go to Settings/Editor/Color Scheme, delete Material Pywal Scheme, import it again form ~/.PyCharm2018.2/config/colors/material-pywal.icls

I also tried hanging the Scheme to anything else and back to Material Pywal and it didn't work.

**Comment by 0x6C38** [comment]
Apparently in version 2018.2, JetBrains decided to start renaming color scheme files to match their color scheme names.
I've changed the color scheme name to match the file name and avoid this issue from the get-go. If you pull the changes, delete the editor color scheme and re-import it, everything should work correctly now.
